In [1]:
import numpy as np
import random
from scipy.linalg import lu
A = np.array([[2, 5, 8, 7, 0], [5, 2, 2, 8, 0], [7, 5, 6, 6, 0], [5, 4, 4, 8, 0], [2, 4, 1, 0, 0]])
p, l, u = lu(A)
print(p)
print(l)
print(u)
a = p.dot(l).dot(u)
print(a)

def new_matrix(m, n, start, end):
    mat = []
    for i in range(m):
        row = []
        for j in range(n):
            x = random.randint(start, end+1)
            row.append(x)
        mat.append(row)
    return np.array(mat)
Z = new_matrix(3,4,1,10)
print('matran k vuong:',Z.shape, ':\n', Z)


[[0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]
[[ 1.          0.          0.          0.          0.        ]
 [ 0.28571429  1.          0.          0.          0.        ]
 [ 0.28571429  0.72        1.          0.          0.        ]
 [ 0.71428571 -0.44       -0.09160305  1.          0.        ]
 [ 0.71428571  0.12        0.19847328  0.75448276  1.        ]]
[[ 7.          5.          6.          6.          0.        ]
 [ 0.          3.57142857  6.28571429  5.28571429  0.        ]
 [ 0.          0.         -5.24       -5.52        0.        ]
 [ 0.          0.          0.          5.53435115  0.        ]
 [ 0.          0.          0.          0.          0.        ]]
[[2. 5. 8. 7. 0.]
 [5. 2. 2. 8. 0.]
 [7. 5. 6. 6. 0.]
 [5. 4. 4. 8. 0.]
 [2. 4. 1. 0. 0.]]
matran k vuong: (3, 4) :
 [[10 10  4  9]
 [ 2 11  2  6]
 [ 9  1  8  8]]


In [9]:
a = np.array([[1,2,3],[2,1,3],[1,3,1]])
print(np.size(a))
print(a)
print(a.shape)


9
[[1 2 3]
 [2 1 3]
 [1 3 1]]
(3, 3)


In [39]:
from numpy.linalg import norm
print(norm(a, ord = 1, axis = 0))
b = np.array([1,2,4])
c = np.array([[1],[2],[3]])
print(norm(b))
print(b.shape)
print(c.shape)
print(c.ndim)


[4. 6. 7.]
4.58257569495584
(3,)
(3, 1)
2


In [48]:
d = [[1,2,3], [2,3,4]]
d_arr = np.array(d)
print(d)
print(d_arr.size)

[[1, 2, 3], [2, 3, 4]]
6


In [55]:
print(a[:,2])
print(a[2])

[3 3 1]
[1 3 1]
